sudo: required
dist: trusty
language: ruby

before_install:
before_install:
- gem install asciidoctor -v 1.5.2
- gem install tilt
- sudo pip install git+https://github.com/gitenberg-dev/gitberg
- sudo pip install pillow
- sudo pip install cssutils
- sudo pip install docutils
- sudo pip install roman
- sudo pip install git+https://github.com/gitenberg-dev/pg-epubmaker
script:
- VERSION=`ruby -e "require 'yaml'; meta = YAML.load_file('metadata.yaml'); puts meta['_version'];"`
- git clone https://github.com/gitenberg-dev/asciidoctor-htmlbook.git
- sudo pip install -r asciidoctor-htmlbook/gitberg-machine/requirements.txt

- /usr/bin/python -c "from gitenberg import travis; travis.build_epub()"
- ebook-convert book.epub book.mobi
- xvfb-run ebook-convert book.epub book.pdf
branches:
  only:
  - master
notifications:
  webhooks:
    urls:
      - https://unglue.it/api/travisci/webhook
    on_success: always
    on_failure: never
    on_start: never
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: RjByvsgTgFFGgrme47RIieo7Jd+cavwVaimGCQg+Rjlh7qP1lXzttvUmrB4etrV1i+4Nl5jGwf62/64j39VQM6R9c4xPf9w8PEjXGxutEw8BB6UDskRViW9hsjE0mqSWwXIOjxSZcixtltk+o7FM0V4cuN6zQvmLFFxnLH6BTOdfjAoBfJOh/QgTEV3tJWn0QO0SjQKOCvpolbsXsKY7OF90iureQ9+H0RjS98EjAWuu5ukrL27t9rXLEQVeRKbQfdSCggh6yaX9fGMrnIJrUkoMQ11TBnSGJSoUhwe7OdSoFLoQ3olizJnIDDLTBv9feqCJkxmNSHm5t+apfHVaVPwcYFPdwEXFpzjL/Kka8VgyxIQdfSHD7SGutV1PG6VbHNf3jmPwjUrYk+vJT1HakdI4+1JoVOHXJGd5XnxS7kKojy3zPCQa5zfSeaGod1/NuSeYrw609t4nHVDEJhGm/Y7pcyNljSQakP4LzRx6teGbApqOY1tvMHCGW7+lXIY1Ty++y29c7zAjBXAmipK//94GVmBijO7HZIRhzcIIzEHEzAZr/VRDU5+ZXPJ2og/8y01iPSA5w3gz3Equhr6JeQ/hgQKtHPjCpcXZtD4cEQRtIdZfmLymYd2gkrgIInfScO67qMSFh6DkCwPQV+/VHRfJtOWHUATGDfmCG4HF1bs=
  file:
    - book.epub
    - book.mobi
    - book.pdf
  "on":
    repo: GITenberg/Democracy-in-America---Volume-1_815
addons:
  apt:
    packages:
    - xsltproc
    - xvfb
    - calibre
    - python-pip
    - git
    - python-dev
    - libjpeg-dev
    - libpng-dev
    - libfreetype6
    - libfreetype6-dev
    - zlib1g-dev
    - python-lxml
    - libxml2-dev
    - libxslt1-dev
    - tidy